In [6]:
import pandas as pd
import numpy as np

anime = pd.read_csv('anime.csv')
rating = pd.read_csv('rating.csv')
anime_modified = anime.set_index('name')

anime_copy = anime.copy(deep=True)

In [29]:
df = pd.DataFrame([[1,'Bob', 'Builder'],
                  [2,'Sally', 'Baker'],
                  [3,'Scott', 'Candle Stick Maker']], 
columns=['id','name', 'occupation'])

df

   id   name          occupation
0   1    Bob             Builder
1   2  Sally               Baker
2   3  Scott  Candle Stick Maker

In [10]:
rating[:10].to_csv('saved_ratings.csv', index=False)

In [13]:
anime.head(5)

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [14]:
rating.tail(3)

         user_id  anime_id  rating
7813734    73515     22145      10
7813735    73516       790       9
7813736    73516      8074       9

In [19]:
len(rating['user_id'].unique())

73515

In [20]:
anime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  object
 2   genre     12232 non-null  object
 3   type      12269 non-null  object
 4   episodes  12294 non-null  object
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB

In [21]:
anime.describe()

           anime_id        rating       members
count  12294.000000  12064.000000  1.229400e+04
mean   14058.221653      6.473902  1.807134e+04
std    11455.294701      1.026746  5.482068e+04
min        1.000000      1.670000  5.000000e+00
25%     3484.250000      5.880000  2.250000e+02
50%    10260.500000      6.570000  1.550000e+03
75%    24794.500000      7.180000  9.437000e+03
max    34527.000000     10.000000  1.013917e+06

In [22]:
anime.type.value_counts()

type
TV         3787
OVA        3311
Movie      2348
Special    1676
ONA         659
Music       488
Name: count, dtype: int64

In [23]:
anime.columns.tolist()

['anime_id', 'name', 'genre', 'type', 'episodes', 'rating', 'members']

In [27]:
anime[['name','episodes']]

                                                    name episodes
0                                         Kimi no Na wa.        1
1                       Fullmetal Alchemist: Brotherhood       64
2                                               Gintama°       51
3                                            Steins;Gate       24
4                                          Gintama&#039;       51
...                                                  ...      ...
12289       Toushindai My Lover: Minami tai Mecha-Minami        1
12290                                        Under World        1
12291                     Violence Gekiga David no Hoshi        4
12292  Violence Gekiga Shin David no Hoshi: Inma Dens...        1
12293                   Yasuji no Pornorama: Yacchimae!!        1

[12294 rows x 2 columns]

In [33]:
df1 = anime[0:2]
df2 = anime[2:4]
pd.concat([df1, df2], ignore_index=True)

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572

In [37]:
rating.merge(anime, left_on='anime_id', right_on='anime_id', suffixes=('_left', '_right'))

,user_id,anime_id,rating_left,name,genre,type,episodes,rating_right,members
0,1,20,-1,Naruto,"Action, Comedy, Martial Arts, Shounen, Super P...",TV,220,7.81,683297
1,3,20,8,Naruto,"Action, Comedy, Martial Arts, Shounen, Super P...",TV,220,7.81,683297
2,5,20,6,Naruto,"Action, Comedy, Martial Arts, Shounen, Super P...",TV,220,7.81,683297
3,6,20,-1,Naruto,"Action, Comedy, Martial Arts, Shounen, Super P...",TV,220,7.81,683297
4,10,20,-1,Naruto,"Action, Comedy, Martial Arts, Shounen, Super P...",TV,220,7.81,683297
...,...,...,...,...,...,...,...,...,...
7813722,65682,30450,8,Dr. Slump: Hoyoyo! Arale no Himitsu Dai Koukai...,"Comedy, Sci-Fi, Shounen",Special,1,6.17,248
7813723,69497,33484,10,Shiroi Zou,"Action, Historical, Kids",Movie,1,4.71,45
7813724,70463,29481,-1,Kakinoki Mokkii,"Fantasy, Kids",Special,1,4.33,61
7813725,72404,34412,-1,Hashiri Hajimeta bakari no Kimi ni,Music,Music,1,6.76,239
7813726,72800,30738,4,Gamba: Gamba to Nakama-tachi,"Adventure, Kids",Movie,1,5.55,185

In [40]:
anime_modified.loc[['Haikyuu!! Second Season','Gintama', 'Under World']]

,anime_id,genre,type,episodes,rating,members
name,,,,,,
Haikyuu!! Second Season,28891,"Comedy, Drama, School, Shounen, Sports",TV,25,8.93,179342
Gintama,918,"Action, Comedy, Historical, Parody, Samurai, S...",TV,201,9.04,336376
Under World,5543,Hentai,OVA,1,4.28,183

In [39]:
anime

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [41]:
anime[anime['rating'] > 8]

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
10765,32230,Xi You Ji,"Adventure, Fantasy",TV,52,8.07,89
10786,26313,Yakusoku: Africa Mizu to Midori,"Drama, Kids",OVA,1,9.25,53
10793,28557,Yamete! Writer Asobi: Doubutsu Mura no Shoubou...,"Drama, Kids",OVA,1,8.67,40
10847,26097,Yume no Tsuzuki,"Drama, Kids",OVA,1,8.67,53
12251,33960,Chou Do M na Hentai Mesu-tachi Otokoton Chouky...,Hentai,OVA,Unknown,8.38,161

In [45]:
anime[anime['rating'] > 8]

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
10765,32230,Xi You Ji,"Adventure, Fantasy",TV,52,8.07,89
10786,26313,Yakusoku: Africa Mizu to Midori,"Drama, Kids",OVA,1,9.25,53
10793,28557,Yamete! Writer Asobi: Doubutsu Mura no Shoubou...,"Drama, Kids",OVA,1,8.67,40
10847,26097,Yume no Tsuzuki,"Drama, Kids",OVA,1,8.67,53
12251,33960,Chou Do M na Hentai Mesu-tachi Otokoton Chouky...,Hentai,OVA,Unknown,8.38,161